export const FETCH_GIPHY_BEGIN = 'FETCH_GIPHY_BEGIN';
export const FETCH_GIPHY_SUCCESS = 'FETCH_GIPHY_SUCCESS';
export const FETCH_GIPHY_FAILURE = 'FETCH_GIPHY_FAILURE';
export const FETCH_GIPHY_DISMISS_ERROR = 'FETCH_GIPHY_DISMISS_ERROR';
